version: '3.7'

services:
#App front developer
  dev-app:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /usr/src/app
    
    restart: unless-stopped

    volumes:
      - ./:/usr/src/app
      
    stdin_open: true
    tty: true
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - network-react-app
