FROM node:18.15.0-alpine3.17 as builder

WORKDIR /usr/src/app

COPY . /usr/src/app

RUN npm install

RUN npm run build

FROM nginx:alpine as production-build

COPY --from=builder /usr/src/app/public /usr/share/nginx/html

COPY ./etc/docker/nginx/default.conf /etc/nginx/conf.d

EXPOSE 8080

ENTRYPOINT ["nginx", "-g", "daemon off;"]